#############################################################################
# Makefile for building: QtSteam
# Generated by qmake (2.01a) (Qt 4.8.4) on: Sat Mar 2 14:30:35 2013
# Project:  QtSteam.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++-64 -o Makefile QtSteam.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1,--sort-common,--as-needed,-z,relro -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		qsteamstate.cpp \
		qtsteammainwindow.cpp \
		state.cpp moc_qtsteammainwindow.cpp \
		moc_state.cpp \
		qrc_ResourcesQtSteam.cpp
OBJECTS       = main.o \
		qsteamstate.o \
		qtsteammainwindow.o \
		state.o \
		moc_qtsteammainwindow.o \
		moc_state.o \
		qrc_ResourcesQtSteam.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		QtSteam.pro
QMAKE_TARGET  = QtSteam
DESTDIR       = 
TARGET        = QtSteam

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_qtsteammainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QtSteam.pro  /usr/share/qt/mkspecs/linux-g++-64/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/release.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -o Makefile QtSteam.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/release.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++-64 -o Makefile QtSteam.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QtSteam1.0.0 || $(MKDIR) .tmp/QtSteam1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QtSteam1.0.0/ && $(COPY_FILE) --parents qsteamstate.h qtsteammainwindow.h state.h .tmp/QtSteam1.0.0/ && $(COPY_FILE) --parents ResourcesQtSteam.qrc .tmp/QtSteam1.0.0/ && $(COPY_FILE) --parents main.cpp qsteamstate.cpp qtsteammainwindow.cpp state.cpp .tmp/QtSteam1.0.0/ && $(COPY_FILE) --parents qtsteammainwindow.ui .tmp/QtSteam1.0.0/ && (cd `dirname .tmp/QtSteam1.0.0` && $(TAR) QtSteam1.0.0.tar QtSteam1.0.0 && $(COMPRESS) QtSteam1.0.0.tar) && $(MOVE) `dirname .tmp/QtSteam1.0.0`/QtSteam1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtSteam1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qtsteammainwindow.cpp moc_state.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qtsteammainwindow.cpp moc_state.cpp
moc_qtsteammainwindow.cpp: qtsteammainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qtsteammainwindow.h -o moc_qtsteammainwindow.cpp

moc_state.cpp: state.h
	/usr/bin/moc $(DEFINES) $(INCPATH) state.h -o moc_state.cpp

compiler_rcc_make_all: qrc_ResourcesQtSteam.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_ResourcesQtSteam.cpp
qrc_ResourcesQtSteam.cpp: ResourcesQtSteam.qrc \
		icons/document-open.svg \
		icons/edit-clear.svg \
		icons/list-add.svg \
		icons/document-new.svg \
		icons/edit-delete.svg \
		icons/window-close.svg \
		icons/go-next.svg \
		icons/document-save.svg \
		icons/edit-redo.svg \
		icons/edit-undo.svg
	/usr/bin/rcc -name ResourcesQtSteam ResourcesQtSteam.qrc -o qrc_ResourcesQtSteam.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_qtsteammainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_qtsteammainwindow.h
ui_qtsteammainwindow.h: qtsteammainwindow.ui
	/usr/bin/uic qtsteammainwindow.ui -o ui_qtsteammainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp qtsteammainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qsteamstate.o: qsteamstate.cpp qsteamstate.h \
		state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsteamstate.o qsteamstate.cpp

qtsteammainwindow.o: qtsteammainwindow.cpp qtsteammainwindow.h \
		ui_qtsteammainwindow.h \
		qsteamstate.h \
		state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtsteammainwindow.o qtsteammainwindow.cpp

state.o: state.cpp state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o state.o state.cpp

moc_qtsteammainwindow.o: moc_qtsteammainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qtsteammainwindow.o moc_qtsteammainwindow.cpp

moc_state.o: moc_state.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_state.o moc_state.cpp

qrc_ResourcesQtSteam.o: qrc_ResourcesQtSteam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_ResourcesQtSteam.o qrc_ResourcesQtSteam.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

