######################################################################
# Automatically generated by qmake (2.01a) mi� sep 12 15:48:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qsteamstate.h qtsteammainwindow.h state.h
FORMS += qtsteammainwindow.ui
SOURCES += main.cpp \
           qsteamstate.cpp \
           qtsteammainwindow.cpp \
           state.cpp
RESOURCES += ResourcesQtSteam.qrc
